import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS Project Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>NextJS Project Starter</h1>
      </main>
    </div>
  )
}
